import * as process from "process"
import type { CodegenConfig } from "@graphql-codegen/cli"

const config: CodegenConfig = {
  overwrite: true,
  schema: [
    {
      [`https://mygpt-be.onrender.com/query` as string]: {
        headers: {
          schema: "true",
          Authorization:
            "Bearer eyJhbGciOiJSUzI1NiIsImtpZCI6Imluc18yUmVQdXZSZENIQnpsTG5lVGowTERLUWs0WnciLCJ0eXAiOiJKV1QifQ.eyJhenAiOiJodHRwOi8vbG9jYWxob3N0OjMwMDAiLCJleHAiOjE2ODgzMDgxNjgsImlhdCI6MTY4ODMwODEwOCwiaXNzIjoiaHR0cHM6Ly9ib2xkLWNhdHRsZS03MS5jbGVyay5hY2NvdW50cy5kZXYiLCJuYmYiOjE2ODgzMDgwOTgsInNpZCI6InNlc3NfMlMxSXdteVBkd3NZclhhTUZQQkF3dlZYMXRaIiwic3ViIjoidXNlcl8yUmVUSnBaeGFzRW5Pc2dPRXVYclRuTUVTc0kifQ.alMoDx42YYkujgnznUV1usQ26fQ50A01NMWn7mbo4xVOxQIex8A_OhTfmTpkIMsIwtmYj3X--u0yjAO7Co0VVG36zxfc4tMmEhq1e2VNCnqdcldvNp-XOP0uTTthN2on64TROGbIAcjlfOB1tm8ghJKDwR3z9VXV2-cFKdWhH5hk33PCSc4WYvO9fugXqP832k2Uq6uyS4XUCC2rZHFLISmuWjs1ZPFohx1zAA-fnM373RbK6HrVBzUujVIoWF8zMk6LRLQOtNLTvYFm68iGaFwqgY3_wYPc8D1L7_vBslShkW2DkTJ78c1wTy2POtq8MLQI-vfUajZ9w5uY8v4q6A",
        },
      },
    },
  ],
  documents: "src/services/graphql/operations/**/*.graphql",
  generates: {
    "src/services/graphql/generated/graphql.ts": {
      plugins: [
        {
          add: {
            content: [
              "/* eslint-disable */",
              "//This Code is auto generated by graphql-codegen, DO NOT EDIT",
              "//You can update the queries or mutations in *.graphql to generate any new changes.",
            ],
          },
        },
        "typescript",
        "typescript-operations",
        "typescript-react-query",
      ],
      config: {
        scalars: {
          Time: "string",
          Any: "unknown",
          Cursor: "string",
          InvalidData: "Record<string, Array<string>>",
          Map: "Record<string, unknown>",
          Date: "string",
        },
        exposeDocument: true,
        exposeMutationKeys: true,
        enumsAsConst: true,
        skipTypename: true,
        inlineFragmentTypes: "combine",
        fetcher: {
          func: "./axiosHelper#useAxios",
          isReactHook: true,
        },
      },
    },
    "./graphql.schema.json": {
      plugins: ["introspection"],
    },
  },
}

export default config
