name: deployment
on:
  push:
    branches:
      - "main"

env:
  IMG_NAME: ${{ github.event.repository.name }}

jobs:
  build:
    name: Build and Deploy App
    runs-on: self-hosted
    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Build Docker Image
        run: |
          docker build -t ${{ env.IMG_NAME }} .

      - name: Serve App
        run: |
          docker container rm -f ${{ env.IMG_NAME }} || true
          docker run -d \
            -e NEXT_PUBLIC_API_URL='${{ secrets.NEXT_PUBLIC_API_URL }}' \
            -e NEXT_PUBLIC_CLERK_PUBLISHABLE_KEY='${{ secrets.NEXT_PUBLIC_CLERK_PUBLISHABLE_KEY }}' \
            -e CLERK_SECRET_KEY=${{ secrets.CLERK_SECRET_KEY }} \
            -e NEXT_PUBLIC_CLERK_SIGN_IN_URL=${{ vars.NEXT_PUBLIC_CLERK_SIGN_IN_URL }} \
            -e NEXT_PUBLIC_CLERK_SIGN_IN_URL=${{ secrets.NEXT_PUBLIC_CLERK_SIGN_IN_URL }} \
            -p 4568:3000 \
            --add-host=host.docker.internal:host-gateway \
            --name ${{ env.IMG_NAME }} ${{ env.IMG_NAME }}
          yes | docker image prune
          yes | docker container prune

